#INCLUDE    <P16F887.INC>

	    LIST    P = 16F887


	__CONFIG    _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
	__CONFIG    _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
	    
	ORG 0X00

CONT3VECES EQU 0X20 ; CUENTA LA CANTIDAD DE VECES QUE SE INTRODUJO MAL EL CODIGO
TEC EQU 0X21 ; GUARDA LA VARIABLE DEL TECLADO 
CLAVE EQU 0X22 
CONTTMR1 EQU 0X23 
CONTTMR2 EQU 0X24
AUXTECLADO EQU 0X25
WTEMP EQU 0X26
STATUSTEMP EQU 0X27
AUXMOVER EQU 0X28
REG0 EQU 0X29
REG1 EQU 0X2A
REG2 EQU 0X2B
REG3 EQU 0X2C
CONTD EQU 0X2D
 
	ORG 0X04
	GOTO ISR
	
	ORG 0X05
	GOTO INICIO
; ----------------- INICIO --------------------------	
INICIO	
	BANKSEL TRISB
	MOVLW 0X01 ; 00000001
	MOVWF TRISB
	CLRF TRISA
	CLRF TRISC
	CLRF TRISD
	BANKSEL PORTB
	CLRF PORTA
	CLRF PORTB
	CLRF PORTC
	CLRF PORTD
	MOVLW .3
	MOVWF CONT3VECES ; ESTA EN EL MISMO BANCO QUE EL PORTB
	MOVLW .256
	MOVWF CONTTMR1
	MOVLW .2
	MOVWF CONTTMR2
	BANKSEL OPTION_REG
	MOVLW 0X07 ; 00000111 REVISAR RBPU
	MOVWF OPTION_REG
	MOVLW 0XB0 ; 10110000
	MOVWF INTCON
LOOP	CALL TECLADO
	CALL TEC7SEG
	CALL MOVER
	CALL MOSTRAR
	GOTO LOOP
;----------------------------- ISR---------------------------------	
ISR	MOVWF WTEMP
	SWAPF STATUS, W
	MOVWF STATUSTEMP
	BTFSC INTCON, T0IF
	GOTO ISRTMR0 ; COMO HACEMOS SI NO QUEREMOS QUE PREGUNTE LO SIGUIENTE 
	BTFSC INTCON, INTF
	GOTO ISRRBO
RET	SWAPF STATUSTEMP, W
	MOVWF STATUS
	SWAPF WTEMP, F
	SWAPF WTEMP, W
	RETFIE
	
ISRRBO	MOVF CLAVE, 0
	SUBWF TECLADO, 0
	BTFSC STATUS, Z
	GOTO LEDVER
	GOTO LEDROJ
VOLVER	BCF INTCON, INTF
	GOTO RET
	
ISRTMR0	DECFSZ CONTTMR1
	GOTO SETTMR0 ; HAY QUE HACERLA
	DECFSZ CONTTMR2
	GOTO RCONT
	GOTO SETTMR0
	
	
;----------------------- SUBRUTINAS -----------------------------
	
	
LEDVER	
	BANKSEL PORTA
	BSF PORTA, 0 ; DEFINIR PUERTO DEL LED VERDE
	MOVLW .3
	MOVWF CONT3VECES
	GOTO VOLVER

LEDROJ	
	BANKSEL PORTA
	BSF PORTA, 1 ; DEFINIR PUERTO DEL LED ROJO
	DECFSZ CONT3VECES, 1
	GOTO VOLVER
	CALL ALARMA ; HAY QUE HACERLO
	BANKSEL TMR0 
	GOTO VOLVER

ALARMA	
	BANKSEL PORTA
	BSF PORTA, 2 ; DEJO BITS 0 Y 1 PARA LOS LEDS
	RETURN
	
	
RCONT	MOVLW .256
	MOVWF CONTTMR1   ;delay de 12.8 seg
	MOVLW .2
	MOVWF CONTTMR2 ; 12,8 * 2 = 25.6 seg
	
	
SETTMR0
	BANKSEL TMR0 
	MOVLW .61 ;  TMR0 Interrumpe cada 50ms
	MOVWF TMR0
	RETURN
	
DELAY 
	BANKSEL PORTA ;PARA IR AL BANCO 0
	MOVLW  .5 ;EL PERIODO DE INSTRUCCION ES DE 1 MICROSEG
	MOVWF CONTD ;ENTONCES HAGO UN DELAY AL REDEDOR DE 5MICROSEG(ES MAYOR)
	DECFSZ CONTD,1
	GOTO $-1
	RETURN
	

TECLADO 
	BANKSEL TRISB
	MOVLW 0X0F		;
	MOVWF TRISB		;
BETA	
	BANKSEL PORTB		;
	MOVLW 0X0F		;
	MOVWF PORTB		;
BACK	MOVLW 0X0F		;
	SUBWF PORTB, 0		;TODO ESTO SE EVITA CON INTERRUPCIONES
	BTFSC STATUS, Z		; SI PONERMOS EL TECLADO EN EL PORTB
	GOTO BACK		; 
	CALL DELAY              ; A CFG DESPUES
	CLRF TEC
	MOVLW 0XEE
	MOVWF AUXTECLADO
ALFA	MOVF AUXTECLADO, 0
	BTFSS W, 0
	GOTO GAMMA
	INCF TEC
	BTFSS W, 1
	GOTO GAMMA
	INCF TEC
	BTFSS W, 2
	GOTO GAMMA
	INCF TEC
	BTFSS W, 3
	GOTO GAMMA
	INCF TEC
	RLF AUXTECLADO
	BTFSS STATUS, C
	GOTO BETA
	GOTO ALFA
GAMMA	MOVF TEC,0
BACK2	MOVF PORTB, 0
	ANDLW 0X0F
	SUBLW 0X0F
	BTFSC STATUS, Z
	GOTO BACK2
	GOTO BETA

TEC7SEG	ADDWF PCL,1 ; asumiendo que el display es catodo comun
	RETLW 0X3F
	RETLW 0X06
	RETLW 0X5B
	RETLW 0X4F
	RETLW 0X66
	RETLW 0X6D
	RETLW 0X7D
	RETLW 0X07
	RETLW 0X7F
	RETLW 0X67

MOVER	
	BANKSEL PORTA
	CLRF AUXMOVER
	MOVWF AUXMOVER
	MOVLW REG2
	MOVWF REG3
	MOVLW REG1
	MOVFW REG2
	MOVLW REG0
	MOVWF REG1
	MOVLW AUXMOVER
	MOVWF REG0
	RETURN

MOSTRAR	MOVLW 0X00
	BANKSEL TRISC
	MOVWF TRISC
	MOVWF TRISB
LOOP1	MOVLW REG3
	BANKSEL PORTC
	MOVWF PORTC
	BSF PORTD, 0
	CALL DELAY ; HAY QUE HACERLO
	CLRF PORTD
	MOVLW REG2
	MOVWF PORTC
	BSF PORTD, 1
	CALL DELAY
	CLRF PORTD
	MOVLW REG1
	MOVWF PORTC
	BSF PORTD, 2
	CALL DELAY
	CLRF PORTD
	MOVLW REG0
	MOVWF PORTC
	BSF PORTD, 3
	CALL DELAY
	CLRF PORTD
	GOTO LOOP1

END



