	#INCLUDE    <P16F887.INC>

	    LIST    P = 16F887


	__CONFIG    _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
	__CONFIG    _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
	    
	ORG 0X00
	AUX EQU 0X20
	CONT EQU 0X21
	AUX2 EQU 0X22
 
	ORG 0X04
	goto ISR
	
	ORG 0X05
	goto INICIO

INICIO goto $
	
	
TECLADO BANKSEL TRISC
	MOVLW 0X0F		;
	MOVWF TRISC		;
BETA	BANKSEL PORTC		;
	MOVLW 0X0F		;
	MOVWF PORTC		;
BACK	MOVLW 0X0F		;
	SUBWF PORTC, 0		;TODO ESTO SE EVITA CON INTERRUPCIONES
	BTFSC STATUS, Z		; SI PONERMOS EL TECLADO EN EL PORTB
	GOTO ATRAS		; 
	CALL DELAY; A CFG DESPUES
	CLRF CONT
	MOVLW 0XEE
	MOVWF AUX
ALFA	MOVF AUX, 0
	BTFSS W, 0
	GOTO GAMMA
	INCF CONT
	BTFSS W, 1
	GOTO GAMMA
	INCF CONT
	BTFSS W, 2
	GOTO GAMMA
	INCF CONT
	BTFSS W, 3
	GOTO GAMMA
	INCF CONT
	RLF AUX
	BTFSS STATUS, C
	GOTO BETA
	GOTO ALFA
GAMMA	MOVF CONT,0
BACK2	MOVF PORTC, 0
	ANDLW 0X0F
	SUBLW 0X0F
	BTFSC STATUS, Z
	GOTO BACK2
	GOTO BETA
	
	
DISPLAY CLRF AUX2   ;??????????????????????
	MOVWF AUX2
	MOVLW REG2
	MOVWF REG3
	MOVLW REG1
	MOVWF REG2
	MOVLW REG0
	MOVWF REG1
	MOVLW AUX2
	MOVWF REG0
	RETURN

